export const categories = [
    {
        id:1,
        name:"Carpentry",
        image:'image1',
    },
    {
        id:2,
        name:"Barber",
        image:'image2',
    },
    {
        id:3,
        name:"Salon",
        image:'image3',
    },
    {
        id:4,
        name:"Sports",
        image:'image4',
    },
    {
        id:5,
        name:"Plumbers",
        image:'image5',
    },
    {
        id:6,
        name:"Others",
        image:'image6',
    },
    {
        id:7,
        name:"Games",
        image:'image7',
    },
    {
        id:8,
        name:"Cars",
        image:'image8',
    },
    {
        id:9,
        name:"Books",
        image:'image9',
    },
    {
        id:10,
        name:"Movies",
        image:'image10',
    },
]

