name: Django CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Set env path based on OS
      run: echo "VENV_PATH=$(if [ "$RUNNER_OS" == "Windows" ]; then echo "env1\\Scripts\\activate"; else echo "env1/bin/activate"; fi)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        python -m venv env1
        source $VENV_PATH
        pip install -r requirements.txt
      working-directory: ./Backend