name: Django CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        cd Backend
        python -m venv env1
        source env1/bin/activate
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        source env1/bin/activate
        python manage.py makemigrations
        python manage.py migrate

    - name: Run server
      run: |
        source env1/bin/activate
        python manage.py runserver